server:
  port: 8071
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service?useSSL=false&serverTimezone=UTC"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

app:
  services:
    profile: http://localhost:8081/profile