server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  datasource:
    url: "jdbc:mysql://localhost:3306/profile_service?useSSL=false&serverTimezone=UTC"
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
